language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-test terragrunt https://gitlab.com/td7x/asdf/terragrunt.git
os:
  - linux
  - osx
