language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-add terragrunt ./
  - asdf list-all terragrunt
  - asdf plugin-test terragrunt ./ 'terragrunt --version'
os:
  - osx
