---
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: clone the plugin repo
        uses: actions/checkout@v1

      - name: clone asdf
        uses: actions/checkout@v1
        with:
          repository: asdf-vm/asdf.git
          ref: refs/heads/master

      - name: Enable asdf
        run: . ../asdf.git/asdf.sh

      - name: Install the plugin
        run: asdf plugin-add terragrunt ./

      - name: List available terragrunt versions
        run: asdf list-all terragrunt

      - name: Test the plugin
        run: asdf plugin-test terragrunt ./ 'terragrunt --version'
