---
name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on:
      - ubuntu-latest
      - macos-latest

    steps:
    - name: clone the plugin repo
      uses: actions/checkout@v1

    - name: clone asdf
      uses: actions/checkout@v1
      with:
        repository: asdf-vm/asdf.git
        ref: refs/heads/master

    - name: Display the current directory contents
      run: ls -alh
