---
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: clone the plugin repo
        uses: actions/checkout@v1

      - name: clone asdf
        uses: actions/checkout@v1
        with:
          repository: asdf-vm/asdf.git
          ref: refs/heads/master

      - name: Setup asdf and run test
        run: |
          . ../asdf.git/asdf.sh
          asdf plugin-add terragrunt ./
          asdf list-all terragrunt
          asdf plugin-test terragrunt ./ 'terragrunt --version'
        shell: bash
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
